version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/vpukhanov/glee/cmd.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
  groups:
    - title: Features
      regexp: "^feat[(\\w)]*!?:"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^fix[(\\w)]*!?:"
      order: 1
    - title: Others
      order: 999

brews:
  - name: glee
    repository:
      owner: vpukhanov
      name: homebrew-tools
      token: '{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}'
    homepage: 'https://github.com/vpukhanov/glee'
    description: "CLI tool to manage Git's local exclude patterns"
    license: 'MIT'
    test: |
      system "#{bin}/glee version"
    install: |
      bin.install "glee"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
